// types/analysis.ts - Analysis Data Types
// Defines structures for Gemini API requests and responses

/**
 * Input media for analysis
 */
export interface AnalysisInput {
    uri: string;           // Local file path
    type: 'video' | 'image';
    mimeType: string;
    fileName: string;
    duration?: number;     // Video duration in seconds
    thumbnailUri?: string; // Generated thumbnail for video
}

/**
 * SEO content generated by Gemini
 */
export interface SEOContent {
    titles: string[];      // 3 suggested titles
    caption: string;       // Ready-to-use caption
    hashtags: string[];    // Relevant hashtags
    filename: string;      // SEO-friendly filename suggestion
}

/**
 * Complete analysis result from Gemini
 */
export interface AnalysisResult {
    // Identification
    id: string;
    createdAt: string;

    // Quantitative Score
    score: number;         // 0-100 viral potential score

    // Qualitative Assessment
    viralPotential: 'Low' | 'Moderate' | 'High' | 'Viral';
    hookStrength: 'Weak' | 'Average' | 'Strong';
    pacing: string;        // e.g., "Fast & engaging", "Too slow start"

    // Content Analysis
    keywords: string[];    // Detected topics/themes
    improvements: string[]; // Actionable feedback bullets

    // Generated SEO Content
    seo: SEOContent;

    // Original input reference
    input: {
        uri: string;
        type: 'video' | 'image';
        fileName: string;
        thumbnailUri?: string;
    };
}

/**
 * Error types for analysis failures
 */
export enum AnalysisErrorType {
    NETWORK_ERROR = 'NETWORK_ERROR',
    TIMEOUT = 'TIMEOUT',
    SAFETY_BLOCK = 'SAFETY_BLOCK',
    PARSE_ERROR = 'PARSE_ERROR',
    FILE_ERROR = 'FILE_ERROR',
    QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
    UNKNOWN = 'UNKNOWN',
}

/**
 * Analysis error structure
 */
export interface AnalysisError {
    type: AnalysisErrorType;
    message: string;
    retryable: boolean;
}

/**
 * Analysis request status
 */
export type AnalysisStatus =
    | 'idle'
    | 'uploading'
    | 'processing'
    | 'completed'
    | 'failed';
